# Arcana: The Three Hearts - Lint Configuration
# PRD 8.1 코드 컨벤션에 따른 엄격한 린트 규칙

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # dynamic 타입 사용 경고
    avoid_dynamic_calls: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # 타입 안전성 (PRD: dynamic 사용 금지)
    avoid_dynamic_calls: true

    # 코드 품질
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    always_declare_return_types: true
    avoid_print: true

    # 가독성
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    # 리소스 관리 (PRD: Dispose 필수)
    cancel_subscriptions: true
    close_sinks: true
